name: .NET

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore Src/Nemcache.Service/Nemcache.Service.csproj
    - name: Build
      run: dotnet build Src/Nemcache.Service/Nemcache.Service.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test Src/Nemcache.Tests/Nemcache.Tests.csproj --no-build --configuration Release
